import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { motion } from 'framer-motion'
import styles from '../styles/Home.module.css'
import { Icon } from '../components/Icon/Icon'
import Card from '../components/Card/Card'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.phone}>
          <div className={styles.grid}>
            <Icon></Icon>
            <Icon></Icon>
            <Icon></Icon>

            {/* <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon>
            <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon>
            <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon>
            <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon>
            <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon>
            <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon>
            <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon>
            <Icon onClick={() => setIsOpen((isOpen) => !isOpen)}></Icon> */}
          </div>
        </div>
      </main>
    </div>
  )
}
