import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Me, Gear, Tinder } from '../components/Icons'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.phone}>
          <div className={styles.grid}>
            <Me />
            <Gear />
            <Tinder />
          </div>
        </div>
      </main>
    </div>
  )
}
